### ISSUE TITLE
Error when parsing Record type

### ISSUE THREAD

**Issue by remarkablemark** [joarwilk/flowgen#155]
index.d.ts:

```ts
declare const foo: Record<string, string>
```

flowgen:

```sh
$ npx flowgen index.d.ts
```

Error:

```
(node:315) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at getFullyQualifiedName (/home/runner/flowgen-error/node_modules/flowgen/lib/printers/node.js:127:68)
    at printType (/home/runner/flowgen-error/node_modules/flowgen/lib/printers/node.js:504:41)
    at Object.fn (/home/runner/flowgen-error/node_modules/flowgen/lib/env.js:10:12)
    at Object.propertyDeclaration (/home/runner/flowgen-error/node_modules/flowgen/lib/printers/declarations.js:46:31)
    at printType (/home/runner/flowgen-error/node_modules/flowgen/lib/printers/node.js:534:36)
    at fn (/home/runner/flowgen-error/node_modules/flowgen/lib/env.js:10:12)
    at Array.map (<anonymous>)
    at parseNameFromNode (/home/runner/flowgen-error/node_modules/flowgen/lib/parse/ast.js:41:86)
    at collectNode (/home/runner/flowgen-error/node_modules/flowgen/lib/parse/index.js:70:51)
    at node.statements.forEach.n (/home/runner/flowgen-error/node_modules/flowgen/lib/parse/index.js:111:34)
(node:315) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:315) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://replit.com/@remarkablemark/flowgen-error-when-parsing-Record

May be related to latest TypeScript version

**Comment by remarkablemark** [comment]
No longer seeing the error after upgrading to the latest version

**Comment by pladaria** [comment]
I am getting this same error on v1.16.0

**Comment by remarkablemark** [comment]
@pladaria I upgraded both and the issue was resolved for me.
