### ISSUE TITLE
Locally installed flowgen breaks jest

### ISSUE THREAD

**Issue by pomali** [joarwilk/flowgen#19]
Maybe it's problem on jest side, I'm not sure, but when I installed flowgen `yarn add -D flowgen` it broke locally installed jest.

```
TypeError: projects.map is not a function
    at Object.<anonymous> (/Users/.../app-js/node_modules/jest-cli/build/cli/runCLI.js:112:28)
    at Generator.next (<anonymous>)
    at step (/Users/.../app-js/node_modules/jest-cli/build/cli/runCLI.js:1:260)
    at /Users/.../app-js/node_modules/jest-cli/build/cli/runCLI.js:1:490
    at Promise (<anonymous>)
    at Object.<anonymous> (/Users/.../app-js/node_modules/jest-cli/build/cli/runCLI.js:1:171)
    at Object.module.exports [as runCLI] (/Users/.../app-js/node_modules/jest-cli/build/cli/runCLI.js:139:50)
    at Object.run (/Users/.../app-js/node_modules/flowgen/node_modules/jest-cli/build/cli/index.js:41:17)
    at Object.<anonymous> (/Users/.../app-js/node_modules/flowgen/node_modules/jest-cli/bin/jest.js:16:25)
    at Module._compile (module.js:573:30)
```

**Comment by orta** [comment]
#16 will fix this
