### ISSUE TITLE
flowtype format failed

### ISSUE THREAD

**Issue by bradennapier** [joarwilk/flowgen#22]
on OSX

https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/uws/index.d.ts

```
flowgen --flow-typed-format uws.ts
Parsing u
Parsing u failed
{ Error: ENOENT: no such file or directory, mkdir '../exports/u_v1.x.x'
    at Object.fs.mkdirSync (fs.js:887:18)
    at exportForFlowTyped (/Users/bradennapier/.nvm/versions/node/v8.8.1/lib/node_modules/flowgen/lib/cli/flow-typed-exporter.js:21:18)
    at /Users/bradennapier/.nvm/versions/node/v8.8.1/lib/node_modules/flowgen/lib/cli/runner.js:77:40
    at Array.forEach (<anonymous>)
    at Object.compile (/Users/bradennapier/.nvm/versions/node/v8.8.1/lib/node_modules/flowgen/lib/cli/runner.js:50:13)
    at Command.<anonymous> (/Users/bradennapier/.nvm/versions/node/v8.8.1/lib/node_modules/flowgen/lib/cli/index.js:25:6)
    at Command.listener (/Users/bradennapier/.nvm/versions/node/v8.8.1/lib/node_modules/flowgen/node_modules/commander/index.js:301:8)
    at emitOne (events.js:115:13)
    at Command.emit (events.js:210:7)
    at Command.parseArgs (/Users/bradennapier/.nvm/versions/node/v8.8.1/lib/node_modules/flowgen/node_modules/commander/index.js:617:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '../exports/u_v1.x.x' }
```

**Comment by hammadj** [comment]
Having this issue as well. @bradennapier were you able to fix it?

**Comment by jackmellis** [comment]
I'm not entirely sure the reasoning for this requirement, but to create a flow-typed definition you  must have an `exports` directory relative to your cwd
