### ISSUE TITLE
Crash with latest release

### ISSUE THREAD

**Issue by orta** [joarwilk/flowgen#65]
When running the danger deploy:

```
TypeError: Cannot read property 'elements' of undefined
    at Import.print (/Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/nodes/import.js:45:60)
    at /Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/cli/compiler.js:23:18
    at Array.map (<anonymous>)
    at compile (/Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/cli/compiler.js:22:39)
    at Object.compileDefinitionFile (/Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/cli/compiler.js:44:12)
    at /Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/cli/runner.js:56:51
    at Array.forEach (<anonymous>)
    at Object.compile (/Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/cli/runner.js:35:13)
    at Command.<anonymous> (/Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/lib/cli/index.js:20:6)
    at Command.listener (/Users/ortatherox/.npm/_npx/23340/lib/node_modules/flowgen/node_modules/commander/index.js:315:8)
```

**Comment by goodmind** [comment]
Fixed in #66

**Comment by goodmind** [comment]
@orta can you close this?

**Comment by orta** [comment]
Cool
